/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e2e2e7',
        'secondary': '#5d5f5f',
        'primary-container': '#1b1b1b',
        'on-error-container': '#93000a',
        'outline': '#7e7576',
        'outline-variant': '#cfc4c5',
        'primary': '#000000',
        'surface': '#f9f9fe',
        'on-surface-variant': '#4c4546',
        'on-surface': '#1a1c1f',
        'surface-bright': '#f9f9fe',
        'secondary-fixed': '#e2e2e2',
        'on-primary': '#ffffff',
        'secondary-container': '#dfe0e0',
        'background': '#f9f9fe',
        'surface-container-high': '#e8e8ed',
        'surface-container': '#ededf2',
        'surface-container-low': '#f3f3f8',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'surface-dim': '#d9dade',
        'on-background': '#1a1c1f',
        'on-primary-container': '#848484',
        'inverse-surface': '#2e3034',
        'tertiary': '#000000',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#e2e2e7',
        'ai-accent': '#A555EE',
        'ai-purple': '#A555EE',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-padding-mobile': '1.5rem',
        'stack-lg': '3rem',
        'container-padding-desktop': '4rem',
        'stack-sm': '0.5rem',
        'stack-md': '1.5rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        'body-sm':    ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-sm':['Inter', 'sans-serif'],
        'headline-md':['Inter', 'sans-serif'],
        'body-md':    ['Inter', 'sans-serif'],
        'label-code': ['Inter', 'sans-serif'],
        'body-lg':    ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-code': ['13px', { lineHeight: '18px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
